# Generated by Django 5.1 on 2025-07-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_ubicacion',
            field=models.CharField(choices=[('oficina', 'Oficina'), ('residencia', 'Residencia')], default='residencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(max_length=20),
        ),
    ]
