# Generated by Django 5.1 on 2025-07-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_reserva_direccion_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_reserva',
            field=models.TimeField(default='08:00'),
        ),
    ]
