# Generated by Django 5.1 on 2025-07-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_reserva_hora_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='direccion',
            field=models.CharField(max_length=250),
        ),
    ]
