# Generated by Django 5.1 on 2025-07-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reserva_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
